services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
volumes:
  dbdata: